In [2]:
import numpy as np

In [74]:
class TicTac:
    
    def __init__(self):
        self.player = 1
        self.action_len = 9
        self.state_len = 9
        self.state = np.zeros([9])
        self.done = False
        
    def reset(self):
        self.player = 1
        self.state = np.zeros([9])
        
    def step(self, location):
        player = self.player
        if(self.state[location] != 0 or self.done):
            return np.copy(self.state), -10, False
        
        self.player = -1 * player
        self.state[location] = player
        reward, done = self.reward_system(location, player)
        self.done = done
        return np.copy(self.state), reward * player, done
        
    def reward_system(self, location, player):
        row = location // 3
        row_win = np.sum(self.state[row*3:(row+1)*3]) == player*3
        
        col = location % 3
        col_win = np.sum(self.state[[col, col+3, col+6]]) == player*3
    
        d1 = np.sum(self.state[[0, 4, 8]]) == player*3
        d2 = np.sum(self.state[[2, 4, 6]]) == player*3
        
        if (row_win or col_win or d1 or d2):
            return 10, True
        elif (len(self.state[self.state == 0]) == 0):
            return 0, True
        else:
            return 1, False

In [75]:
env = TicTac()

In [76]:
len(env.state[env.state == 0])

9

In [83]:
state, reward, done = env.step(8)
print(state.reshape(3, 3))
print(reward)

[[ 1. -1.  0.]
 [ 1. -1.  1.]
 [ 0. -1.  0.]]
-10


In [67]:
env.reset()

In [46]:
env.state

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])