In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression

In [3]:
bias = 100

X, y, coef = make_regression(100000, n_features=500, n_informative=500, bias=bias, noise = 4, random_state=42, coef=True)

In [4]:
expected_theta = np.hstack([[bias], coef])

In [5]:
expected_theta

array([1.00000000e+02, 7.05342636e+01, 5.63753386e+01, 9.20026517e+01,
       9.79938466e+00, 3.50173829e+01, 8.62392346e+01, 9.92766643e+01,
       7.31982558e+01, 4.44957818e+01, 5.67147120e+01, 4.18671206e+01,
       1.62000516e+01, 2.52596924e+01, 7.75219662e+01, 7.89374729e+01,
       7.99952268e+01, 8.33215552e+01, 3.48890072e-01, 4.17987432e+01,
       8.02225501e+00, 5.97437113e+01, 4.26130386e+01, 5.08329926e+01,
       7.47483170e+01, 3.59184140e+01, 5.25971445e+01, 5.65443186e+01,
       6.55977797e+01, 3.21940268e+01, 2.08793938e+01, 6.34317460e+01,
       7.60387465e+01, 7.23923439e+01, 7.35243410e+01, 8.39239259e+01,
       2.19734125e+00, 6.59534828e+00, 7.48155281e+01, 4.53016978e+01,
       7.66323848e+00, 2.42338552e+01, 9.40928555e+01, 8.47124835e+01,
       7.37509797e+00, 1.84242583e+01, 8.11697155e+01, 8.70394402e+01,
       8.92989799e+01, 4.17433020e+01, 8.78556187e+01, 7.62293296e+01,
       9.05820000e+01, 2.47271675e+01, 6.58703720e+01, 1.92514334e+01,
      

In [6]:
X_update = np.hstack([np.ones((X.shape[0], 1)), X])

In [7]:
X_update[0]

array([ 1.        , -1.11646428, -0.72848601,  0.43236769,  0.93867914,
        0.0790213 , -0.39956814, -0.73530968,  1.84355815,  0.15260877,
       -1.42400887,  0.16942827, -1.46546332, -0.6708353 , -0.25163239,
        0.7456012 ,  1.24435532,  0.31674619,  0.11781536,  0.8090541 ,
       -0.22214137,  0.02934813, -0.05737298,  2.21719638, -0.94820883,
       -0.23552181, -0.24398874, -0.61159543, -1.2149031 ,  1.08928349,
       -0.60754931,  0.540491  , -0.64513033, -1.0682221 , -0.6633365 ,
        0.54412037, -0.211635  ,  0.31347073,  1.2208361 ,  0.72734646,
       -0.14689886, -1.24432651,  0.953882  ,  0.44476202, -1.19242011,
        0.30550937, -0.21761077,  0.04823519, -0.20486828,  0.30457491,
       -0.98847067,  0.13161662,  0.63082441, -1.04177542,  0.67685572,
        0.83816368, -1.27329166,  0.58895569, -0.88442399,  0.36133674,
       -0.56216606,  0.77864376, -0.73193645,  0.81725569, -1.85242365,
        0.59218998, -0.24292155,  0.02530818,  1.18004419,  1.71

In [8]:
expected_theta

array([1.00000000e+02, 7.05342636e+01, 5.63753386e+01, 9.20026517e+01,
       9.79938466e+00, 3.50173829e+01, 8.62392346e+01, 9.92766643e+01,
       7.31982558e+01, 4.44957818e+01, 5.67147120e+01, 4.18671206e+01,
       1.62000516e+01, 2.52596924e+01, 7.75219662e+01, 7.89374729e+01,
       7.99952268e+01, 8.33215552e+01, 3.48890072e-01, 4.17987432e+01,
       8.02225501e+00, 5.97437113e+01, 4.26130386e+01, 5.08329926e+01,
       7.47483170e+01, 3.59184140e+01, 5.25971445e+01, 5.65443186e+01,
       6.55977797e+01, 3.21940268e+01, 2.08793938e+01, 6.34317460e+01,
       7.60387465e+01, 7.23923439e+01, 7.35243410e+01, 8.39239259e+01,
       2.19734125e+00, 6.59534828e+00, 7.48155281e+01, 4.53016978e+01,
       7.66323848e+00, 2.42338552e+01, 9.40928555e+01, 8.47124835e+01,
       7.37509797e+00, 1.84242583e+01, 8.11697155e+01, 8.70394402e+01,
       8.92989799e+01, 4.17433020e+01, 8.78556187e+01, 7.62293296e+01,
       9.05820000e+01, 2.47271675e+01, 6.58703720e+01, 1.92514334e+01,
      

In [9]:
class LinearRegression:
    
    def __init__(self, lr=.1, itrs=1000):
        self.lr = lr
        self.itrs = itrs
    
    def fit(self, X, y):
        self.X = X
        self.y = y.reshape(-1, 1)
        
        first = np.dot(X.T, X)
        second = np.dot(X.T, y)
        
        self.theta = np.dot(np.linalg.pinv(first), second)
       
    
    def predict(self, X):
        return LinearRegression.hypothesis(X, self.theta).flatten()
        

    def error(self):
        yh = LinearRegression.hypothesis(self.X, self.theta)
        return np.sum((yh - self.y) ** 2)
    
    @classmethod
    def hypothesis(cls, X, theta):
        return np.dot(X, theta)
        
    

In [10]:
model = LinearRegression(lr=.1, itrs=100)
model.fit(X_update, y)

In [11]:
yh = model.predict(X_update)

In [12]:
# plt.scatter(X, y)
# plt.scatter(X, yh)

In [13]:
# plt.plot(errors)

In [14]:
model.theta

array([100.00003697,  63.05314435,  84.18731049,  89.26025505,
        41.25509275,  11.39557089])

In [15]:
expected_theta

array([100.        ,  63.05278127,  84.18283846,  89.25875697,
        41.260929  ,  11.40206714])