In [2]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.preprocessing import OneHotEncoder

In [7]:
line = np.random.randint(0, 10, 100)

In [8]:
ohe = OneHotEncoder(categories="auto")

In [10]:
ohe.fit(line.reshape(-1, 1))

OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [11]:
ohe.categories_

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [16]:
line[:4]

array([3, 9, 0, 7])

In [15]:
ohe.transform(line.reshape(-1, 1)).todense()

matrix([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],


In [17]:
line

array([3, 9, 0, 7, 3, 9, 8, 2, 8, 3, 7, 0, 5, 3, 2, 4, 7, 9, 1, 1, 5, 9,
       6, 4, 9, 3, 5, 1, 1, 5, 3, 9, 9, 9, 7, 7, 1, 5, 7, 7, 2, 8, 2, 6,
       3, 0, 9, 2, 9, 0, 5, 4, 2, 9, 1, 5, 8, 2, 8, 0, 4, 5, 6, 7, 3, 8,
       9, 6, 3, 8, 3, 3, 5, 0, 4, 2, 8, 3, 2, 6, 1, 8, 8, 0, 0, 9, 2, 8,
       2, 7, 6, 8, 3, 8, 5, 8, 5, 8, 7, 0])