In [20]:
import pandas as pd
from keras.models import Model
from keras.layers import Dense
from keras.layers import Input
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv("../datasets/mnist_train_small.csv").values

In [3]:
X = data[:, 2:]
y = data[:, 1]

In [56]:
ohe = OneHotEncoder(categories="auto")
y_hot = ohe.fit_transform(y.reshape(-1, 1)).todense()
y_sec = ohe.fit_transform(((y>5).astype(int)).reshape(-1, 1)).todense()

In [36]:
# X_train, X_test, y_train, y_test = train_test_split(
# ...     X, y_hot, test_size=0.33, random_state=42)

In [57]:
y_sec.shape

(8000, 2)

In [58]:
in_layer = Input(shape=[784])
layer_1 = Dense(200, activation="tanh")(in_layer)
layer_21 = Dense(50, activation="tanh")(layer_1)
layer_22 = Dense(50, activation="tanh")(layer_1)
out_1 = Dense(10, activation="softmax")(layer_21)
out_2 = Dense(2, activation="softmax")(layer_22)

In [59]:
model = Model(inputs=[in_layer], outputs=[out_1, out_2])

In [60]:
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            (None, 784)          0                                            
__________________________________________________________________________________________________
dense_16 (Dense)                (None, 200)          157000      input_4[0][0]                    
__________________________________________________________________________________________________
dense_17 (Dense)                (None, 50)           10050       dense_16[0][0]                   
__________________________________________________________________________________________________
dense_18 (Dense)                (None, 50)           10050       dense_16[0][0]                   
__________________________________________________________________________________________________
dense_19 (

In [61]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["acc"])

In [62]:
hist = model.fit(X, [y_hot, y_sec], epochs=10, batch_size=200)

Epoch 1/10
8000/8000 [==============================] - 1s 98us/step - loss: 1.7374 - dense_19_loss: 1.2797 - dense_20_loss: 0.4577 - dense_19_acc: 0.6054 - dense_20_acc: 0.7790
Epoch 2/10
8000/8000 [==============================] - 0s 37us/step - loss: 0.9281 - dense_19_loss: 0.6314 - dense_20_loss: 0.2967 - dense_19_acc: 0.8328 - dense_20_acc: 0.8802
Epoch 3/10
8000/8000 [==============================] - 0s 44us/step - loss: 0.7307 - dense_19_loss: 0.4799 - dense_20_loss: 0.2509 - dense_19_acc: 0.8661 - dense_20_acc: 0.9036
Epoch 4/10
8000/8000 [==============================] - 0s 43us/step - loss: 0.6584 - dense_19_loss: 0.4183 - dense_20_loss: 0.2401 - dense_19_acc: 0.8829 - dense_20_acc: 0.9073
Epoch 5/10
8000/8000 [==============================] - 0s 44us/step - loss: 0.5637 - dense_19_loss: 0.3596 - dense_20_loss: 0.2041 - dense_19_acc: 0.8985 - dense_20_acc: 0.9240
Epoch 6/10
8000/8000 [==============================] - 0s 39us/step - loss: 0.5264 - dense_19_loss: 0.3307 - 

In [63]:
hist.history

{'loss': [1.7373977690935134,
  0.9281056061387062,
  0.730747039616108,
  0.6583710864186287,
  0.5636782675981522,
  0.5264152467250824,
  0.49665984362363813,
  0.4876860357820988,
  0.4633534006774426,
  0.44315257370471955],
 'dense_19_loss': [1.2796543821692468,
  0.631394562125206,
  0.4798966936767101,
  0.418256975710392,
  0.35961395800113677,
  0.3307404648512602,
  0.3159865356981754,
  0.3125216536223888,
  0.2973952922970057,
  0.28019142150878906],
 'dense_20_loss': [0.4577433817088604,
  0.29671104811131954,
  0.25085034742951395,
  0.24011411219835282,
  0.2040643110871315,
  0.19567478355020285,
  0.18067330904304982,
  0.17516437973827123,
  0.16595811024308205,
  0.1629611538723111],
 'dense_19_acc': [0.6053749993443489,
  0.8327500015497208,
  0.8661250010132789,
  0.8828749984502793,
  0.8984999984502793,
  0.9047499984502793,
  0.9122499987483025,
  0.9102500006556511,
  0.9109999999403954,
  0.916750006377697],
 'dense_20_acc': [0.7790000021457673,
  0.880249999

In [64]:
out = model.predict(X[:10])

In [65]:
o1 = out[0]
np.argmax(o1, axis=1)

array([0, 4, 1, 9, 2, 1, 3, 1, 4, 3])

In [66]:
o2 = out[1]
np.argmax(o2, axis=1)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [51]:
y[:10]

array([0, 4, 1, 9, 2, 1, 3, 1, 4, 3])

In [52]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [53]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [54]:
y_test[:10]

array([9, 1, 4, 8, 0, 8, 2, 2, 4, 8])

In [55]:
y_test2[:10]

array([9, 1, 4, 8, 0, 8, 2, 2, 4, 8])