In [ ]:
! python3 -m pip install numpy

In [2]:
# imports

import numpy as np

In [3]:
oneD = np.array([0, 1, 4, 7])

In [4]:
oneD = np.array(range(5))

In [5]:
oneD

array([0, 1, 2, 3, 4])

In [14]:
twoD = np.array([range(0, 5), range(15, 20)])

In [16]:
twoD.dtype

dtype('int64')

In [19]:
a = np.arange(50).reshape(10, -1)

In [21]:
a.shape

(10, 5)

In [22]:
a.ndim

2

In [23]:
a[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
a[:, 1:7] = 0

In [27]:
a

array([[ 0,  0,  0,  3,  4],
       [ 5,  0,  0,  8,  9],
       [10,  0,  0, 13, 14],
       [15,  0,  0, 18, 19],
       [20,  0,  0, 23, 24],
       [25,  0,  0, 28, 29],
       [30,  0,  0, 33, 34],
       [35,  0,  0, 38, 39],
       [40,  0,  0, 43, 44],
       [45,  0,  0, 48, 49]])

In [31]:
one = np.arange(20).reshape(5, -1)
two = np.arange(40, 60).reshape(5, -1)

In [33]:
two

array([[40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [34]:
np.hstack([one, two])

array([[ 0,  1,  2,  3, 40, 41, 42, 43],
       [ 4,  5,  6,  7, 44, 45, 46, 47],
       [ 8,  9, 10, 11, 48, 49, 50, 51],
       [12, 13, 14, 15, 52, 53, 54, 55],
       [16, 17, 18, 19, 56, 57, 58, 59]])

In [35]:
np.vstack([one, two])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [38]:
one + 10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [48]:
one  + np.array(range(5)).reshape(-1, 1)

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [51]:
np.max(one)

19

In [52]:
np.min(one)

0

In [54]:
np.min(one, axis=1)

array([ 0,  4,  8, 12, 16])

In [57]:
np.mean(one, axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [58]:
one

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [60]:
np.std(one, axis=0)

array([5.65685425, 5.65685425, 5.65685425, 5.65685425])

In [62]:
data = np.linspace(0, 2*np.pi, 10)

In [63]:
np.sin(data)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])