In [21]:
from keras.models import Sequential
from keras.layers import Dense
from keras.losses import categorical_crossentropy
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../datasets/mnist_train_small.csv").values

In [4]:
X = data[:, 2:]
y = data[:, 1]

In [5]:
ohe = OneHotEncoder(categories="auto")

In [6]:
y_hot = ohe.fit_transform(y.reshape(-1, 1)).todense()

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y_hot, test_size=0.33, random_state=42)

In [8]:
X.shape

(8000, 784)

In [16]:
layer_1 = Dense(100, activation="tanh", input_shape=[X.shape[1]])
layer_3 = Dense(50, activation="tanh")
layer_4 = Dense(y_hot.shape[1], activation="softmax")
model = Sequential()
model.add(layer_1)
model.add(layer_3)
model.add(layer_4)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 100)               78500     
_________________________________________________________________
dense_10 (Dense)             (None, 50)                5050      
_________________________________________________________________
dense_11 (Dense)             (None, 10)                510       
Total params: 84,060
Trainable params: 84,060
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [18]:
model.fit(X_train, y_train, epochs=40, batch_size=100)

Epoch 1/40
5360/5360 [==============================] - 0s 77us/step - loss: 1.4047 - acc: 0.5690
Epoch 2/40
5360/5360 [==============================] - 0s 27us/step - loss: 0.7789 - acc: 0.7823
Epoch 3/40
5360/5360 [==============================] - 0s 25us/step - loss: 0.6056 - acc: 0.8336
Epoch 4/40
5360/5360 [==============================] - 0s 36us/step - loss: 0.5166 - acc: 0.8537
Epoch 5/40
5360/5360 [==============================] - 0s 33us/step - loss: 0.4648 - acc: 0.8631
Epoch 6/40
5360/5360 [==============================] - 0s 30us/step - loss: 0.4360 - acc: 0.8703
Epoch 7/40
5360/5360 [==============================] - 0s 28us/step - loss: 0.4052 - acc: 0.8787
Epoch 8/40
5360/5360 [==============================] - 0s 31us/step - loss: 0.3755 - acc: 0.8920
Epoch 9/40
5360/5360 [==============================] - 0s 46us/step - loss: 0.3760 - acc: 0.8927
Epoch 10/40
5360/5360 [==============================] - 0s 41us/step - loss: 0.3688 - acc: 0.8877
Epoch 11/40
5360/53

In [15]:
model.evaluate(X_test, y_test)

2640/2640 [==============================] - 0s 64us/step


[0.27953068352106847, 0.9106060606060606]

In [24]:
np.argmax(model.predict(X_test[:1]), axis=1)

array([9])

In [25]:
y_test[0]

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
model.predict(X_test[:1])

array([[5.1847459e-05, 1.4866289e-04, 5.9731694e-05, 8.4275166e-03,
        1.1633551e-02, 6.3753032e-05, 2.7206208e-06, 1.1170775e-02,
        6.9423988e-03, 9.6149904e-01]], dtype=float32)

[logo 5e6d3f7] keras
 4 files changed, 984 insertions(+)
 create mode 100644 lecture_14/.ipynb_checkpoints/MLP-checkpoint.ipynb
 create mode 100644 lecture_14/.ipynb_checkpoints/mnist-checkpoint.ipynb
 create mode 100644 lecture_14/MLP.ipynb
 create mode 100644 lecture_14/mnist.ipynb
Everything up-to-date
